/**
	Routing module generated by angular cli with some routes added.
**/

import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { MainForumComponent } from './main-forum/main-forum.component';
import { SubmissionComponent } from './submission/submission.component';
import { ThreadComponent } from './thread/thread.component';

const routes: Routes = [
	{ path: '', component: MainForumComponent, pathMatch: 'full'},
	{ path: 'submission', component: SubmissionComponent},
	{ path: 'thread/:id', component: ThreadComponent},
	{ path: 'empty', component: ThreadComponent}
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
