/**

	This is the main component generated by angular cli.

**/

import { Component } from '@angular/core';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: []
})
export class AppComponent {
	title = 'discussion-forum';
}
