/**

	Main module generated by angular cli.

**/

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { FormsModule } from '@angular/forms';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { MainForumComponent } from './main-forum/main-forum.component';
import { SubmissionComponent } from './submission/submission.component';
import { NavbarComponent } from './navbar/navbar.component';
import { ThreadComponent } from './thread/thread.component';
import { ReplacePipe } from './replace.pipe';
import { TimeSincePipe } from './time-since.pipe';
import { HandlePluralPipe } from './handle-plural.pipe';

@NgModule({
  declarations: [
    AppComponent,
    MainForumComponent,
    SubmissionComponent,
    NavbarComponent,
    ThreadComponent,
	ReplacePipe,
	TimeSincePipe,
	HandlePluralPipe
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
	HttpClientModule,
	FormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
